#! /bin/bash

set -e

echo "Starting cleanup"

# Cleanup build-time dependencies
apt-get remove --purge -y openjdk-7-jdk time curl libz-dev m4 sbcl ant file
apt-get autoremove -y
rm -rf /var/lib/apt



