#! /bin/bash

set -ex

if [ -z "${ECL_VERSION}" ]; then
    exit 0
fi

_URL=https://common-lisp.net/project/ecl/static/files/release/ecl-${ECL_VERSION}.tgz

cd /usr/local/src/

curl "${_URL}" | tar xzf -

cd /usr/local/src/ecl-${ECL_VERSION}

patch -p1 < /tmp/lisp-installers/patches/ecls-16.1.3-build.patch

./configure --prefix=/usr/local --with-system-gmp --enable-longdouble=yes --with-dffi
make -j1
make install
make clean
