#! /bin/bash

set -e

if [ -z "${SBCL_VERSION}" ]; then
    exit 0
fi

WORKDIR=/usr/local/src

_URL=http://iweb.dl.sourceforge.net/project/sbcl/sbcl/${SBCL_VERSION}/sbcl-${SBCL_VERSION}-source.tar.bz2

mkdir -p ${WORKDIR}
cd ${WORKDIR}

curl "${_URL}" | tar xjf -

cd ${WORKDIR}/sbcl-${SBCL_VERSION}
sh make.sh --prefix=/usr/local --fancy
sh install.sh

# Cleanup intermediate files.
rm -rf output
rm -rf obj
