#! /bin/bash

set -ex

if [ -z "${SBCL_VERSION}" ]; then
    exit 0
fi

WORKDIR=/usr/local/src

_URL=https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VERSION}/sbcl-${SBCL_VERSION}-source.tar.bz2

mkdir -p ${WORKDIR}
cd ${WORKDIR}

curl -L "${_URL}" | tar xjf -

cd ${WORKDIR}/sbcl-${SBCL_VERSION}

patch -p1 < /tmp/lisp-installers/patches/concurrency-test-1.5.3.patch

sh make.sh --prefix=/usr/local --fancy
sh install.sh

# Cleanup intermediate files.
rm -rf output
rm -rf obj
